name: egofets
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.10
  - h5py
  - pandas
  - numpy
  - scipy
  - matplotlib
  - seaborn
  - jupyter
  - ipykernel
  - pip
  - python-docx
  - pymupdf
  - streamlit
