"""Reader for Keithley 2600 SourceMeter HDF5 output."""

import json
from dataclasses import dataclass, field
from pathlib import Path

import h5py
import numpy as np
import pandas as pd

from ..readers_core import Measurement
from .base import Reader


def _parse_measurement_name(name: str) -> dict[str, str]:
    parts = name.split("_", 1)
    batch_dev = parts[0] if len(parts) > 1 else ""
    info = {"batch": "", "device": ""}
    for part in batch_dev.replace("Dispositivo", "Dev").split("_"):
        if part.startswith("Batch"):
            info["batch"] = part
        elif part.startswith("Dev"):
            info["device"] = part
    return info


def _curve_to_dataframe(group: h5py.Group) -> pd.DataFrame:
    records = {}
    for ds_name in group.keys():
        data = group[ds_name][:]
        label = ds_name.replace("measured_", "").replace("calculated_", "")
        records[label] = data
    df = pd.DataFrame(records)
    for attr_name, attr_val in group.attrs.items():
        if attr_name not in ("measurement_counter", "timestamp"):
            df[attr_name] = attr_val
    return df


class Keithley2600Reader(Reader):
    """Reader for HDF5 files generated by a Keithley 2600 SourceMeter setup.

    The file structure expected is:
        /<MeasurementName>/           ← group with metadata attrs
            /curve_000/               ← curve group
                measured_V_GS          ← datasets (numpy arrays)
                measured_V_DS
                measured_I_DS
                measured_I_GS
                calculated_V_GS
                calculated_V_DS
                time
                (attrs: V_DS or V_GS depending on mode)
            /curve_001/
            ...
    Or for stability measurements:
        /<MeasurementName>/           ← group with metadata attrs
            I_DS                      ← datasets directly
            I_GS
            V_DS
            V_GS
            time
    """

    name = "keithley2600"
    description = "Keithley 2600 SourceMeter HDF5 output (transfer/output/stability)"

    def can_read(self, filepath: Path) -> bool:
        if not super().can_read(filepath):
            return False
        try:
            with h5py.File(filepath, "r") as f:
                for key in f.keys():
                    obj = f[key]
                    if not isinstance(obj, h5py.Group):
                        continue
                    attrs = dict(obj.attrs)
                    if any(a in attrs for a in ("measurement_mode", "DS_channel", "channel_DS")):
                        return True
                    for sub in obj.values():
                        if isinstance(sub, h5py.Group) and sub.keys():
                            return True
            return False
        except Exception:
            return False

    def read(self, filepath: Path) -> dict[str, Measurement]:
        filepath = Path(filepath)
        measurements = {}

        with h5py.File(filepath, "r") as f:
            for top_name in f.keys():
                group = f[top_name]

                info = _parse_measurement_name(top_name)
                mode = group.attrs.get("measurement_mode", "")
                has_curves = any(
                    isinstance(group[k], h5py.Group) and k.startswith("curve_")
                    for k in group.keys()
                )

                if has_curves:
                    dfs = []
                    curves_info = []
                    for curve_name in sorted(group.keys()):
                        if not curve_name.startswith("curve_"):
                            continue
                        cg = group[curve_name]
                        df = _curve_to_dataframe(cg)
                        df["curve"] = curve_name
                        df["timestamp"] = cg.attrs.get("timestamp", "")
                        dfs.append(df)

                        curve_info = {"name": curve_name}
                        for an, av in cg.attrs.items():
                            if an not in ("measurement_counter", "timestamp"):
                                curve_info[an] = av
                        curves_info.append(curve_info)

                    full_df = pd.concat(dfs, ignore_index=True)
                    metadata = {
                        an: av
                        for an, av in group.attrs.items()
                        if an not in ("measurement_mode", "timestamp", "description")
                    }
                    metadata["reader"] = self.name

                    m = Measurement(
                        name=top_name,
                        mode=mode,
                        batch=info["batch"],
                        device=info["device"],
                        data=full_df,
                        metadata=metadata,
                        curves=curves_info,
                    )
                else:
                    records = {}
                    for ds_name in group.keys():
                        data = group[ds_name][:]
                        label = ds_name.replace("measured_", "")
                        records[label] = data
                    df = pd.DataFrame(records)
                    timestamp = group.attrs.get("timestamp", "")
                    if "timestamp" not in df.columns and timestamp:
                        df["timestamp"] = timestamp

                    metadata = {
                        an: av
                        for an, av in group.attrs.items()
                        if an not in ("timestamp", "description")
                    }
                    metadata["reader"] = self.name

                    m = Measurement(
                        name=top_name,
                        mode=mode if mode else "stability",
                        batch=info["batch"],
                        device=info["device"],
                        data=df,
                        metadata=metadata,
                    )

                measurements[top_name] = m

        return measurements
